### ISSUE TITLE
需要重新安装pycurl

### ISSUE THREAD

**Issue by fanyizhen1995** [JoeShi/aws-serverless-image-handler#1]
**问题**：运行 lambda 会报错：pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (nss)

**问题原因**：AWS 升级了 Lambda 环境 ( 详情参加 https://github.com/awslabs/serverless-image-handler/issues/127).

**解决方法**：重新编译安装 pycurl，然后打包源代码。

**具体步骤**：在 Linux 环境下运行指令

```
PYCURL_SSL_LIBRARY=openssl pip install pycurl -t pycurl
cd pycurl
cp * <你的源代码文件夹>
```

在第一步执行的之前需要确保系统中已经安装了 libcurl-devel 和 openssl-devel，若没有安装则通过以下指令安装:

```
yum install libcurl-devel
yum install openssl-devel
```

**Comment by JoeShi** [comment]
是amazon linux 1么？我记得是

**Comment by fanyizhen1995** [comment]
对的，我查了下大部分是runtime是在 amz linux 上，新出的 runtime，比如 nodejs.12.x 这种是在 amz linux 2 上。
[https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)

然后 lambda 升级环境这件事是今年7月的事情。
